### PR TITLE
Add CODEOWNERS.

### PR DESCRIPTION
**Pull request by marcferna**
Just adding CODEOWNERS so people on the list will be requested when a new PR is opened. Adding you @gauravs @erezny @skukx since you were the ones that engaged the most on the style conversations. Happy to remove you if you don't want to involved or to add someone else that I might've missed

### CODE REVIEW

**Comment by marcferna** [comment]
Also, I added that at least 2 approving reviews are necessary in order to merge PRs...that might be too much but I wanted to have consensus when style changes are requested

**Review by gauravs — APPROVED** [review]
LGTM, happy to review style changes

**Review by skukx — APPROVED** [review]

**Comment by skukx** [comment]
Doesn't look like my approval counts 😢

**Comment by marcferna** [comment]
> Doesn't look like my approval counts 😢

Fixed 👍

**Pull request merged**
